/**
 * Created by yangke on 2017/9/28.
 */

api = {
    global_config:{//全局配置
        modify:"/api/global_config/modify",
        themeModify:"/api/user/modify_theme",
    },
    project:{//工程接口
        create:"/api/project/create",
        getTree:"/api/project/tree",
        modify:"/api/project/modify",
        del:"/api/project/delete",
        move:"/api/project/move",

    },
    dashboard:{//仪表盘
        getList:"/api/dashboard/list",
        getInfo:"/api/dashboard/info",
        create:"/api/dashboard/create",
        modify:"/api/dashboard/modify",
        del:"/api/dashboard/delete",
        move:"/api/dashboard/move",
        hide:"/api/dashboard/hide",
    },
    chart:{//工作表
        getInfo:"/api/chart/info",
        getData:"/api/chart/data",
        create:"/api/chart/create",
        copy:"/api/chart/copy",
        del:"/api/chart/delete",
        modify:"/api/chart/modify",
        getDbInfo:"/api/chart/database_info",
        modifyTb:"/api/chart/modify_tb",
        getRelationList:"/api/chart/rela_list",
        search:"/api/chart/search",
        getSizeGroups:"/api/chart/size_groups",
        getGisSizeGroups:"/api/chart/size_groups",
        addRelaTb:"/api/chart/add_rela_tb",
        delRelaTb:"/api/chart/del_rela_tb",
        exportExcelType:"/api/export/get_file_type",
        exportLargeExcel:"/api/export/large_file",
        wholeRelaChain:"/api/chart/whole_rela_chain",
        tableUnion:"/api/chart/table_union",
        cmpDateRange:"/api/chart/filter_cmp_date_range",
    },
    db: {//数据库
        getField: "/api/dstb/info",
        del: "/api/dstb/delete",
        getList: "/api/dstb/list",
        modify: "/api/dstb/modify",
        getUpdateRecord: "/api/excel/list?time:" + (new Date).getTime(),
        deleteFile: "/api/dstb/delete_file",
        excelCreate: "/api/excel/create",
        excelAppend: "/api/excel/append",
        excelReplace: "/api/excel/replace",
        excelHistoryReplace: "/api/excel/replace_one",
        excelDelete: "/api/excel/delete",
        startTask: "/api/dstb/start",
        excelCheck: "/api/excel/check",
        excelModify: "/api/excel/modify",
        subOwnWbList: "/api/folder/sub_own_list",
        extractTb: "/api/tb/extract",
        shareTbInfo: "/api/tb/share_info",
        uploadPreview: "/api/excel/preview",
        uploadParser: "/api/excel/parser",
        getSchema: "/api/tb/schema",
        checkFieldDependency: "/api/tb/check_field_dependency",
        adjustTable: "/api/",
        previewAdjustTable: "/api/excel/replace_preview",
        excelRepeatCheck: "/api/excel/title_check"
    },
    tb:{//表单
        modify: "/api/tb/modify",
        modifyFieldStatus: "/api/tb/field_selected/modify",
        getStatusData: "/api/tb/field_selected/query",
        getList: "/api/tb/list",
        copy: "/api/data_union/union_copy",
        getInfo: "/api/tb/info",
        getMultiInfo: "/api/tb/multi_info",
        preview: "/api/tb/preview",
        del: "/api/tb/delete",
        delTableWithChart: "/api/tb/delete",
        getJoinInfo: "/api/tb/join_info",
        getJoinErrorReport: "/api/wb/profile",
        getJoinProfileReport: "/api/wb/profile_report",
        getModelStruct: "/api/tb/model_struct",
        getStatus: "/api/tb/status",
        getStorageAccount: "/api/tb/stat",
        modifyTag: "/api/tb/modify_tag",
        getTbsField: "/api/dstb/infos",
        partitionSet: "/api/tb/partition/set",
        partitionDel: "/api/tb/partition/remove",
        wholeJoinChain: "/api/tb/whole_join_chain",
        sqlTrans: "/api/tb/sql_trans",
        sqlScript: "/api/sql_script/check",
        sqlFormat: "/api/sql_script/format",
        tableFieldFilter: "/api/field/filter",
        batchMove: "/api/folder/change_batch",
        batchDeleteTables: "/api/tb/delete_batch",
        checkTablesRely: "/api/tb/list_check_rely",
        gisTransfer: "/api/gis/transfer",
        gisModify: "/api/gis/modify",
        updateModeCheck: "/api/tb/update_mode/check",
        updateModeModify: "/api/tb/update_mode/modify",
        getPartitionNum: "/api/tb/partition/num",
        triggerFullUpdate: "/api/tb/update",
        replaceCheck: "/api/wb/replace_check",
        getTplExcel: "/api/personal/tpl_excel",
        tplExport: "/api/personal/export",
        modelCheck: "/api/data_aggr/model_check",
        viewExec: "/api/view/exec",
        uploadRenameFields: "/api/field/upload_templete",
        exportSmallTbFile: "/api/tb/export_tb",
        exportTbFile: "/api/export/tb_file",
        parseCode: "/api/general/create",
        getFieldParseCode: "/api/general/info",
        joinTbPreview: "/api/wb/preview",
        joinTbCreate: "/api/wb/create",
        joinTbInfo: "/api/dstb/info",
        joinTbCheckPreview: "/api/wb/modify_preview",
        joinTbModify: "/api/wb/modify"
    },
    field:{//字段
        getList: "/api/tb/info",
        getEditableSchema: "/api/tb/editable_schema",
        create: "/api/field/create",
        modify: "/api/field/modify",
        del: "/api/field/delete",
        getRange: "/api/field/range",
        getFilteredRange: [
            "/api/enum_color/gis_field_range",
            "/api/enum_color/field_range"
        ],
        url_preview: "/api/field/url_preview",
        extract_preview: "/api/field/extract_preview",
        extract_url: "/api/field/extract_url",
        merge: "/api/field/merge",
        getAggregatorLen: "/api/field/get_length"
    },
    share:{
        allList: "/api/share/all_list",
        getList: "/api/share/list",
        share: "/api/share/commit",
        modify: "/api/share/modify",
    },
    ds:{//数据源
        getConnStatus: "/api/ds/conn",
        connNopwd: "/api/ds/nopawd",
        createApi: "/api/ds/create",
        getNameAndTag: "/api/ds/list",
        getList: "/api/ds/list",
        getListForDataSource: "/api/ds/nslist",
        getTree: "/api/ds/tree",
        info: "/api/ds/info",
        modify: "/api/ds/modify",
        startSyncTask: "/api/ds/sync",
        startBaiduSyncCost: "/api/rtapi/single_cost",
        del: "/api/ds/delete",
        getInitInfo: "/api/ds/all",
        getResultForSearch: "api/ds/search",
        getTables: "/api/ds/mdstb",
        getJsjTables: "/api/ds/cdstb",
        modifytb: "/api/ds/modifytb",
        openDataList: "/api/ds/publiclist",
        create: "/api/ds/create",
        conn: "/api/ds/conn",
        tbList: "/api/ds/tblist",
        username_verify: "/api/ds/verify",
        jyw_klist: "/api/jyw/klist",
        set_sync: "/api/ds/sync",
        mobile_default_bind: "/api/sms/defaultbind",
        mobile_unbind_all: "/api/sms/unbindall",
        warn_mobile_list: "/api/sms/list",
        warn_mobile_del: "/api/sms/delete",
        warn_mobile_vcode: "/api/sms/vcode",
        warn_mobile_verify: "/api/sms/verify",
        ds_amount: "/api/ds/stat",
        kstList: "/api/kst/list",
        kstConn: "/api/kst/conn",
        kstCreate: "/api/kst/create",
        kstInfo: "/api/kst/info",
        kstModify: "/api/kst/modify",
        baiduRegion: "/api/rtapi/city",
        baiduIndex: "/api/inapi/city",
        baiduIndexCheckKeyWords: "/api/inapi/check",
        modifyDbBaiduSearchTask: "/api/rtapi/control",
        modifyDbBaiduIndexTask: "/api/inapi/control",
        baiduSearchConfig: "/api/rtapi/config",
        baiduIndexConfig: "/api/inapi/config",
        modifyDbBaiduSearch: "/api/rtapi/modify",
        modifyDbBaiduIndex: "/api/inapi/modify",
        createDbBaiduSearch: "/api/ds/create",
        createDbBaiduSearchTask: "/api/rtapi/create",
        createDbBaiduIndexTask: "/api/inapi/create",
        deleteDbBaiduSearchTask: "/api/rtapi/delete",
        deleteDbBaiduIndexTask: "/api/inapi/delete",
        getDbBaiduSearchTaskList: "/api/rtapi/rtlist",
        getDbBaiduIndexTaskList: "/api/inapi/inlist",
        startBaiduTaskSyncCost: "/api/rtapi/single_cost",
        startBaiduIndexTaskSyncCost: "/api/inapi/single_cost",
        startBaiduSyncTask: "/api/rtapi/sync",
        startBaiduIndexSyncTask: "/api/inapi/sync",
        baiduCompanySetting: "/api/rtapi/field_info",
        modifyCompanySetting: "/api/rtapi/field_modify",
        wechatDs: {//微信
            createWechatIndex: "/api/ds/create",
            deleteWechatTask: "/api/wechat/delete",
            getTaskList: "/api/wechat/inlist",
            modifyWechatTask: "/api/wechat/modify",
            createWechatTask: "/api/wechat/create",
            wechatIndexConfig: "/api/wechat/config",
            wechatTaskSwitchControl: "/api/wechat/control"
        },
        toutiaoDs: {//头条
            createToutiaoIndex: "/api/ds/create",
            deleteToutiaoTask: "/api/toutiao/delete",
            getTaskList: "/api/toutiao/inlist",
            modifyToutiaoTask: "/api/toutiao/modify",
            createToutiaoTask: "/api/toutiao/create",
            toutiaoIndexConfig: "/api/toutiao/config",
            toutiaoTaskSwitchControl: "/api/toutiao/control"
        },
        indexDs: {
            getUrl: {
                70: {
                    create: "/api/web/create",
                    inlist: "/api/web/inlist",
                    control: "/api/web/control",
                    delete: "/api/web/delete",
                    config: "/api/web/config",
                    modify: "/api/web/modify",
                }
            },
            getTaskList: "/api/index/inlist",
            createTask: "/api/index/create",
            switchTask: "/api/index/control",
            deleteTask: "/api/index/delete",
            getTaskInfo: "/api/index/config",
            modifyTask: "/api/index/modify",
            checkKeyWords: "/api/index/check",
            areaList: "/api/index/city",
        },
        weiboDs: {
            deleteTask: "/api/toutiao/delete",
            getTaskList: "/api/web/inlist",
            modifyTask: "/api/toutiao/modify",
            createToutiaoTask: "/api/toutiao/create",
            toutiaoIndexConfig: "/api/toutiao/config",
            toutiaoTaskSwitchControl: "/api/toutiao/control"
        },
        dbTypeInfo: "/api/ds/category",
        getCTableList: "/api/ds/cdstb",
        getTbInfo: "/api/ds/tbinfo",
        getDsSheet: "/api/ds/sheet",
        getDsTask: "/api/ds/task",
        delete: "/api/ds/delete",
        getGaReports: "/api/ga/dreports",
        getGaInfo: "/api/ga/info",
        previewGa: "/api/ga/preview",
        getBdpDeployCodeToken: "/api/journal/token",
        pwdBatchPreview: "/api/ds_batch/preview",
        pwdBatchModify: "/api/ds_batch/modify",
        saveUserSync: "/api/ds/usersync",
        getJumpInfo: "/api/chart/jump_info",
        saveJumpInfo: "/api/chart/jump_save",
        delJumpInfo: "/api/chart/jump_delete",
        checkJumpInfo: "/api/chart/jump_check",
        getCodeImg: "/api/ds/specialsync"
    },
    ds_field : {//数据源字段
    field_list: "/api/ds_field/field_list",
    field_del:"/api/ds_field/field_del",
    field_modify:"/api/ds_field/field_modify",
    },
    adv_date : {
        del:"/api/adv_date/del",
        global_del:"/api/adv_date/del",
        modify:"/api/adv_date/modify",
        global_modify:"/api/adv_date/modify",
        list:"/api/adv_date/list",
        info:"/api/adv_date/info",
        order:"/api/adv_date/order"
    },
    warn : {
        add:"/api/warn/add",
        modify:"/api/warn/modify",
        del:"/api/warn/delete",
        warnSwitch:"/api/warn/switch",
    },
    model : {
        modify:"/api/model/modify",
        preview:"/api/model/train_set_preview",
        result:"/api/model/result",
        list:"/api/model/list",
        info:"/api/model/info",
        del:"/api/model/delete",
        saveClusterRs:"/api/model/result_commit",
    },
    folder : {
        getList:"/api/folder/list",
        del:"/api/folder/delete",
        modify:"/api/folder/modify",
        create:"/api/folder/create",
        change:"/api/folder/change",
        change_batch:"/api/folder/change_batch",
        modify_folder_rel:"/api/folder/modify_folder_rel",
        modify_seq:"/api/folder/modify_seq",
        modify_parent:"/api/folder/modify_parent",
        getStructure:"/api/folder/get_tree",
        getStructureWithParam:"/api/folder/get_tree_with_tblist",
        getWorktable:"/api/folder/list_only_tb",
        getTableSiblings:"/api/folder/get_current_tb",
        getTableFolderInfo:"/api/folder/info",
        searchFolderAndTable:"/api/folder/search",
        filterFolderAndTable:"/api/folder/filter",
    },
    fieldComment : {
        create:"/api/field_comment/create",
        modify:"/api/field_comment/modify",
        del:"/api/field_comment/delete",
    },
    dash_global_filter : {
        list:"/api/dsh_filter/list",
        modify:"/api/dsh_filter/commit",
        item:"/api/dsh_filter/item",
        range:"/api/dsh_filter/range",
    },
    user : {
        userList:"/api/sub/list",
        modifyPersonal:"/api/user/modify_personal",
        modifyInfo:"/api/user/modify_info",
        groupList:"/api/group/list",
        modify:"/api/sub/modify",
        setFrozen:"/api/user/set_frozen",
        exportFileList:"/api/export/file_list",
        exportDelTask:"/api/export/delete",
        hideNotification:"/api/export/hide_notification",
        logout:"/api/user/logout",
        modifyPassword:"/api/user/modify_pwd",
        getUserInfo:"/api/user/info",
        unreadNewFeatures:"/api/log/unread",
        readNewFeatures:"/api/log/read",
        getMobileCode:"/api/user/gen_captcha",
    },
    enumField : {
        getOrderInfo:"/api/enum_order/info",
        updateOrder:"/api/enum_order/update",
        getFilteredOrderInfo:"/api/enum_order/filter_info",
    sql_script : {
        preview:"/api/sql_script/preview",
        create:"/api/sql_script/create",
        modifyPreview:"/api/sql_script/modify_preview",
        modify:"/api/sql_script/modify",
        checkIncrease:"/api/sql_script/check_tb_increment",
    },
    tpl : {
        ruleTbInfo:"/api/tb/rule_tb_info",
        getFieldRule:"/api/rule/search_filter",
        saveBatchRule:"/api/rule/create_filter_batch",
        chartList:"/api/chart/list",
        tplCommit:"/api/template/commit",
    },
    workspace : {
        tbListPreview:"/api/workspace/tb_list_preview",
        create:"/api/workspace/create",
        delete:"/api/workspace/delete",
        modify:"/api/workspace/modify",
        info:"/api/workspace/info",
        list:"/api/workspace/list",
        modifyDashList:"/api/workspace/modify_dash_list",
        modifyTableList:"/api/workspace/modify_tb_list",
        modifyGroupList:"/api/workspace/modify_group_list",
        modifyAuthority:"/api/workspace/modify_authority_info",
        userList:"/api/workspace/user_list",
        workspaceLog:"/api/workspace/ws_log",
    },
    sem : {
        list:"/api/sem/list",
        merge:"/api/sem/merge",
        tbrefer:"/api/sem/tbrefer",
    },
    guide : {
        guideSet:"/api/user/guide_set",
        getDashDemo:"/api/personal/demo",
    },
    notice : {
        getListByType:"/api/message/list",
        setNoticeReaded:"/api/message/read",
        getNoticeType:"/api/message/purpose",
    },
    authority : {
        info:"/api/auth/info",
        create:"/api/auth/create",
        modify:"/api/auth/modify",
        stop:"/api/auth/stop",
        oplog:"/api/auth/oplog",
    },
    account : {
        userInfo:"/api/sub/info",
        userList:"/api/sub/list",
        userCreate:"/api/sub/create",
        userModify:"/api/sub/modify",
        userDelete:"/api/sub/delete",
        userDelTbCheck:"/api/sub/del_tb_check",
        setFrozen:"/api/user/set_frozen",
        resetPwd:"/api/user/reset_pwd",
        sentNotice:"/api/sub/send_notice",
        accountLimit:"/api/account/limit",
        groupList:"/api/group/list",
        groupOrder:"/api/group/order",
        groupInfo:"/api/group/info",
        groupCreate:"/api/group/create",
        removeAdminCheck:"/api/group/check_remove_admin",
        groupModify:"/api/group/modify",
        groupDelete:"/api/group/delete",
        groupDelTbCheck:"/api/group/del_tb_check",
        securityInfo:"/api/security/info",
        securityCreate:"/api/security/create",
        securityDelete:"/api/security/delete",
        securityList:"/api/security/list",
        securityPreCheck:"/api/security/pre_check",
        securityModify:"/api/security/modify",
        tbShareFieldCheck:"/api/share/cancel_fields_check",
        tbShareFilterCheck:"/api/share/check",
        getGroupCustomFields:"/api/group/list_fields",
        updateGroupCustomFields:"/api/group/update_fields",
        groupMutiOpt:"/api/group/muti_opt",
    },
    chart_tpl : {
        info:"/api/chart_tpl/info",
        createChart:"/api/chart_tpl_apply/create",
        create:"/api/chart_tpl/create",
        delete:"/api/chart_tpl/delete",
        modify:"/api/chart_tpl/modify",
        applyList:"/api/chart_tpl_apply/list",
        typeList:"/api/chart_tpl/type_list",
    },
    chart_tpl_project : {
        getTree:"/api/chart_tpl_proj/tree",
        create:"/api/chart_tpl_proj/create",
        modify:"/api/chart_tpl_proj/modify",
        del:"/api/chart_tpl_proj/delete",
        order:"/api/chart_template/order",
        move:"/api/chart_template/move",
    },
    chartTplRule : {
        info:"/api/chart_tpl_rule/info",
        industryList:"/api/industry/list",
        domainList:"/api/domain/list",
        domainSearch:"/api/domain/search",
        create:"/api/chart_tpl_rule/create",
        list:"/api/chart_tpl_rule/list",
        delete:"/api/chart_tpl_rule/delete",
        modify:"/api/chart_tpl_rule/modify",
        issued:"/api/chart_tpl_rule/issued"
    },
    pay : {
        personalVipInfo:"/api/pay/personal_vip_info",
        personalOrderHistory:"/api/pay/order_history",
        getMemberRightData:"/pmresources/personal-config/member.json",
        personalInvoice:"/api/receipt/create",
        personalInvoiceHistory:"/api/receipt/list",
    },
    view : {
        preview:"/api/view/preview",
        create:"/api/view/create",
        modify:"/api/view/modify",
        info:"/api/view/info",
    },
    getJobStatus: "/api/job/status",
    getTaskStatus: "/api/task/status",
    getFunctionList: "/api/function/list"
};